#!/bin/bash
# by maravento.com

# Mount | Umout google drive folder

# https://www.maravento.com/2018/11/compartir-google-drive-con-samba.html
# how to use (not sudo/root)
#./gdrive start
#./gdrive stop

# replace "my_user" with yout username unix account
myuser="your_user"
# replace "GoogleDrive" with your (path) GoogleDrive Folder
GD="/home/$myuser/GoogleDrive"

case "$1" in
  start)
    echo 'Mount Google Drive...'
    # Optional (If the folder does not exist)
    if [ ! -d $GD ]; then mkdir -p $GD && chmod 777 $GD; fi
    google-drive-ocamlfuse $GD
    echo "OK"
    exit
  ;;
  stop)
    echo 'Umount Google Drive...'
    fusermount -u $GD
    echo "OK"
    exit
  ;;
  *)
  echo "Usage: ./gdmu {start|stop}"
 exit 1
 ;;
 esac
 exit 0
